/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sbml.libsbml;

public class SBMLDocumentPlugin extends SBasePlugin {
   private long swigCPtr;

   protected SBMLDocumentPlugin(long cPtr, boolean cMemoryOwn)
   {
     super(libsbmlJNI.SBMLDocumentPlugin_SWIGUpcast(cPtr), cMemoryOwn);
     swigCPtr = cPtr;
   }

   protected static long getCPtr(SBMLDocumentPlugin obj)
   {
     return (obj == null) ? 0 : obj.swigCPtr;
   }

   protected static long getCPtrAndDisown (SBMLDocumentPlugin obj)
   {
     long ptr = 0;

     if (obj != null)
     {
       ptr             = obj.swigCPtr;
       obj.swigCMemOwn = false;
     }

     return ptr;
   }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsbmlJNI.delete_SBMLDocumentPlugin(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  
  /**
   *  Constructor
   * <p>
   * @param uri the URI of package 
   * @param prefix the prefix for the given package
   * @param sbmlns the {@link SBMLNamespaces} object for the package
   */
 public SBMLDocumentPlugin(String uri, String prefix, SBMLNamespaces sbmlns) {
    this(libsbmlJNI.new_SBMLDocumentPlugin__SWIG_0(uri, prefix, SBMLNamespaces.getCPtr(sbmlns), sbmlns), true);
  }

  
  /**
   * Copy constructor. Creates a copy of this object.
   */
 public SBMLDocumentPlugin(SBMLDocumentPlugin orig) {
    this(libsbmlJNI.new_SBMLDocumentPlugin__SWIG_1(SBMLDocumentPlugin.getCPtr(orig), orig), true);
  }

  
  /**
   * Creates and returns a deep copy of this {@link SBMLDocumentPlugin} object.
   * <p>
   * @return a (deep) copy of this object
   */
 public SBasePlugin cloneObject() {
    long cPtr = libsbmlJNI.SBMLDocumentPlugin_cloneObject(swigCPtr, this);
    return (cPtr == 0) ? null : new SBMLDocumentPlugin(cPtr, true);
  }

  
  /**
   * <p>
   * Returns the bool value of 'required' attribute of corresponding 
   * package in {@link SBMLDocument} element.
   * <p>
   * @return the bool value of 'required' attribute of corresponding
   * package in {@link SBMLDocument} element.
   */
 public boolean getRequired() {
    return libsbmlJNI.SBMLDocumentPlugin_getRequired(swigCPtr, this);
  }

  
  /**
   * <p>
   * Sets the bool value of 'required' attribute of corresponding package
   * in {@link SBMLDocument} element.
   * <p>
   * @param value the bool value of 'required' attribute of corresponding 
   * package in {@link SBMLDocument} element.
   * <p>
   * @return integer value indicating success/failure of the
   * function.  The possible values
   * returned by this function are:
   * <li> {@link  libsbmlConstants#LIBSBML_OPERATION_SUCCESS LIBSBML_OPERATION_SUCCESS }
   * <li> {@link  libsbmlConstants#LIBSBML_UNEXPECTED_ATTRIBUTE LIBSBML_UNEXPECTED_ATTRIBUTE }
   */
 public int setRequired(boolean value) {
    return libsbmlJNI.SBMLDocumentPlugin_setRequired(swigCPtr, this, value);
  }

}
